#!/bin/bash
ofuscate_fun () {
number=$(expr length $1)
for ((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
if [ "${txt[$i]}" = "." ]; then
txt[$i]="#"
else
 if [ "${txt[$i]}" = "#" ]; then
txt[$i]="."
 fi
fi
if [ "${txt[$i]}" = "1" ]; then
txt[$i]="@"
else
 if [ "${txt[$i]}" = "@" ]; then
txt[$i]="1"
 fi
fi
if [ "${txt[$i]}" = "2" ]; then
txt[$i]="?"
else
 if [ "${txt[$i]}" = "?" ]; then
txt[$i]="2"
 fi
fi
if [ "${txt[$i]}" = "3" ]; then
txt[$i]="&"
else
 if [ "${txt[$i]}" = "&" ]; then
txt[$i]="3"
 fi
fi
if [ ! -e $HOME/tmp ]; then
touch $HOME/tmp
fi
echo -ne "${txt[$i]}" >> $HOME/tmp
done
txtofus=$(cat $HOME/tmp)
if [ -e $HOME/tmp ]; then
rm $HOME/tmp
fi
link_list=$(echo $txtofus | rev)
}
rm $(pwd)/$0
#===============================#
#a="$[1+($RANDOM%100)]"
link_txt="https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/ADM-MANAGER-ULTIMATE-BETA/Install/curiosidades"
cor[1]="\033[1;36m"
cor[2]="\033[1;33m"
cor[3]="\033[1;31m"
cor[4]="\033[0m"
#===============================#
cd $HOME
wget -O textos $link_txt -o /dev/null
_cont="1"
while read sd_var; do
txt[$_cont]="$sd_var"
_cont=$(($_cont + 1))
done < $HOME/textos
rm $HOME/textos
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} INSTALADOR ADM-SCRIPTS ®"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} Iniciando Instalação..."



echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
sleep 3s
echo -ne "${cor[4]}"

key[1]=$(echo "$key_key" | awk -F "∆" '{print $2}')
key[2]=$(echo "$key_key" | awk -F "∆" '{print $1}')
ofuscate_fun ${key[2]}
echo -e "${cor[2]} Verificando Key: ${cor[3]}$key_key"
wget -O lista https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/ADM-MANAGER-ULTIMATE-BETA/Install/lista -o /dev/null
if [ "$(cat $HOME/lista | grep $link_list/${key[1]})" = "" ]; then
echo -e "${cor[2]} INVALIDA, saindo..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠\033[0m"
sleep 2s
exit
fi
echo -e "${cor[2]} OK, key: ${cor[3]}$key_key${cor[2]} Valida! Instalando..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"



sleep 3s
echo ""
echo -e "${cor[3]}UMA CURIOSIDADE!!!"
echo -e "${cor[2]} ${txt[$[1+($RANDOM%100)]]}"
echo ""
sleep 4s
if [ -d /etc/adm-lite ]; then
rm -rf /etc/adm-lite
fi
mkdir /etc/adm-lite
cd /etc/adm-lite
echo "cd /etc/adm-lite && bash ./menu" > /bin/menu
echo "cd /etc/adm-lite && bash ./menu" > /bin/adm
chmod +x /bin/menu
chmod +x /bin/adm
_contador="1"
while read arq_adm; do
cd /etc/adm-lite
wget $arq_adm -o /dev/null
if [ "$_contador" = "5" ]; then
echo -e "${cor[3]}MAIS UMA CURIOSIDADE!!!"
echo -e "${cor[2]} ${txt[$[1+($RANDOM%100)]]}"
echo ""
sleep 4s
_contador="1"
fi
_contador=$(($_contador + 1))
done < $HOME/lista
unset _contador
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} Agora Sera Instalado As Dependencias"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
cd /etc/adm-lite
chmod +x ./*
apt-get install screen -y > /dev/null 2>&1
bash ./instalar & > /dev/null 2>&1
while true; do
echo -ne "${cor[1]}["
 for ((q=1; q <= 40 ; q++)); do
 echo -ne "${cor[3]}X"
 sleep 0.5s
 done
if [ -e $HOME/fim ]; then
echo -ne "${cor[1]}] - \033[1;32m[OK][100%]"
break
 else
echo -ne "${cor[1]}] - ${cor[3]}Aguarde!"
echo ""
fi
done
rm $HOME/fim
rm $HOME/lista
echo -e "
${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[2]} Deseja Instalar Painel De Upload?"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
read -p " [ s | n ]: " up_load
if [[ "$up_load" = "s" || "$up_load" = "S" ]]; then
bash /etc/adm-lite/insta_painel
fi
echo -e "
${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} Perfeito, Agora Presizamos Selecionar 1 Tipo de Instalação!!!"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} |1|• ${cor[2]}OPENSSH + PROXY"
echo -e "${cor[3]} |2|• ${cor[2]}DROPBEAR + PROXY"
echo -e "${cor[3]} |3|• ${cor[2]}OPENVPN + OPENSSH + PROXY"
cd /etc/adm-lite
echo -ne "${cor[1]}"
while true; do
read -p " [ 1~3 ]: " xadm
case $xadm in
1)
source openssh_proxy
break
;;
2)
source dropbear_proxy
break
;;
3)
source openvpn_proxy
break
;;
esac
done
exit