#!/bin/bash
rm -rf $HOME/instalarold
cd
if [ $(id -u) != 0 ]
then
echo "Ejecte este script como root"
exit
fi

fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

inst_pct () {
mkdir /etc/VpsPackdir 2>/dev/null 
mkdir /etc/VpsPackdir/limite 2>/dev/null 
mkdir /etc/VpsPackdir/senha 2>/dev/null 
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/VPSPACK-SERVER-V2.0/Modulos/limite -O /bin/limite 
chmod +x /bin/limite
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/VPSPACK-SERVER-V2.0/Modulos/criarusuario -O /bin/criarusuario 
chmod +x /bin/criarusuario
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/VPSPACK-SERVER-V2.0/Modulos/deletarusuario -O /bin/deletarusuario 
chmod +x /bin/deletarusuario
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/VPSPACK-SERVER-V2.0/Modulos/redefinirusuario -O /bin/redefinirusuario 
chmod +x /bin/redefinirusuario
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/VPSPACK-SERVER-V2.0/Modulos/vps -O /bin/vps 
chmod +x /bin/vps
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/VPSPACK-SERVER-V2.0/Modulos/speedtest.py -O /bin/speedtest.py 
chmod +x /bin/speedtest.py
}

clear
echo -e "\033[0;34m ===================================\033[0m"
echo -e "\033[1;30m INSTALANDO VPSPACK-SERVER V2.0!\033[0m"
echo -e "\033[0;34m ===================================\033[0m"
echo -e "\033[1;33m Aguarde...\033[1;32m"
fun_bar 'inst_pct'
clear
echo -e "\033[0;34m =============================================================\033[0m"
echo -e "\033[1;30m VPSPACK-SERVER V2.0!\033[0m"
echo -e "\033[0;34m =============================================================\033[0m"
echo -e "\033[1;32m Instalacion concluida\n\033[1;30m Execute vps:"
echo -e "\033[0;34m =============================================================\033[0m"
echo -e "\033[1;31m • \033[1;37mvps\033[1;36m Menu de Opciones de Administracion\033[01;37m"
echo -e "\033[1;31m • \033[1;37mcriarusuario\033[1;33m Crear Usuario Con Fecha y limite de conexion\033[01;37m"
echo -e "\033[1;31m • \033[1;37mdeletarusuario\033[1;33m Eliminar usuario o solo desconectar\033[01;37m"
echo -e "\033[1;31m • \033[1;37mredefinirusuario\033[1;33m Editar un usuario\033[01;37m"
echo -e "\033[1;31m • \033[1;37mlimite\033[1;33m Limite de conexiones simultaneas\033[01;37m"
echo -e "\033[0;34m =============================================================\033[0m"
rm -rf $HOME/instalarold
