#!/bin/bash

instalar_fun () {
apt-get update -y > /dev/null 2>&1
apt-get upgrade -y > /dev/null 2>&1
apt-get install python -y > /dev/null 2>&1
apt-get install lsof -y > /dev/null 2>&1
apt-get install -y python3-pip -y > /dev/null 2>&1
apt-get install nmap -y > /dev/null 2>&1
apt-get install figlet -y > /dev/null 2>&1
apt-get install bc -y > /dev/null 2>&1
apt-get install lynx -y > /dev/null 2>&1
apt-get install curl -y > /dev/null 2>&1
apt-get install zip -y > /dev/null 2>&1
apt-get install apache2 -y > /dev/null 2>&1
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
touch $HOME/fim
exit
}

remover_fun () {
if [[ -e /etc/openvpn/server.conf ]]; then
openvpn_proxy 1
fi
apt-get update -y > /dev/null 2>&1
apt-get upgrade -y > /dev/null 2>&1
apt-get purge python -y > /dev/null 2>&1
apt-get install -y python3-pip -y > /dev/null 2>&1
apt-get purge screen -y > /dev/null 2>&1
apt-get purge nmap -y > /dev/null 2>&1
apt-get purge figlet -y > /dev/null 2>&1
apt-get purge zip -y > /dev/null 2>&1
apt-get purge bc -y > /dev/null 2>&1
apt-get purge lynx -y > /dev/null 2>&1
apt-get purge curl -y > /dev/null 2>&1
apt-get purge squid -y > /dev/null 2>&1
apt-get purge squid3 -y > /dev/null 2>&1
apt-get purge dropbear -y > /dev/null 2>&1
apt-get purge apache2 -y > /dev/null 2>&1
apt-get purge php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
rm -rf /etc/adm-lite
touch $HOME/fim
exit
}

if [ "$1" = "" ]; then
instalar_fun
fi
if [ "$1" = "0" ]; then
remover_fun
fi