#!/bin/bash
#zip $HOME/$1.zip $HOME/$1.ovpn
atualiza_fun () {
insta_arquivos1="/etc/adm-server"
insta_arquivos2="/etc/adm-server/adm-ultimate"
ofuscate_fun () {
number=$(expr length $1)
for ((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
if [ "${txt[$i]}" = "." ]; then
txt[$i]="#"
else
 if [ "${txt[$i]}" = "#" ]; then
txt[$i]="."
 fi
fi
if [ "${txt[$i]}" = "1" ]; then
txt[$i]="@"
else
 if [ "${txt[$i]}" = "@" ]; then
txt[$i]="1"
 fi
fi
if [ "${txt[$i]}" = "2" ]; then
txt[$i]="?"
else
 if [ "${txt[$i]}" = "?" ]; then
txt[$i]="2"
 fi
fi
if [ "${txt[$i]}" = "3" ]; then
txt[$i]="&"
else
 if [ "${txt[$i]}" = "&" ]; then
txt[$i]="3"
 fi
fi
if [ ! -e $HOME/tmp ]; then
touch $HOME/tmp
fi
echo -ne "${txt[$i]}" >> $HOME/tmp
done
txtofus=$(cat $HOME/tmp)
if [ -e $HOME/tmp ]; then
rm $HOME/tmp
fi
link_list=$(echo $txtofus | rev)
}
#===============================#
#a="$[1+($RANDOM%100)]"
link_txt="http://www.bnetservice.com.mx/adm/curiosidades"
cor[1]="\033[1;36m"
cor[2]="\033[1;33m"
cor[3]="\033[1;31m"
cor[4]="\033[0m"
#===============================#
cd $HOME
wget -O textos $link_txt -o /dev/null
_cont="1"
while read sd_var; do
txt[$_cont]="$sd_var"
_cont=$(($_cont + 1))
done < $HOME/textos
rm $HOME/textos
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} Atualizar Base Server ADM®"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} Iniciando Procedimento..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -ne "${cor[4]}"
read -p " DIGITE A KEY: " key_key
key[1]=$(echo "$key_key" | awk -F "∆" '{print $2}')
key[2]=$(echo "$key_key" | awk -F "∆" '{print $1}')
ofuscate_fun ${key[2]}
echo -e "${cor[2]} Verificando Key: ${cor[3]}$key_key"
wget http://${link_list}/${key[1]}/server.zip -o /dev/null
if [ ! -e "$HOME/server.zip" ]; then
echo -e "${cor[2]} key invalida, saindo..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠\033[0m"
sleep 2s
exit
fi
echo -e "${cor[2]} OK, key: ${cor[3]}$key_key${cor[2]} Valida! Instalando..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
sleep 3s
echo ""
echo -e "${cor[3]}UMA CURIOSIDADE!!!"
echo -e "${cor[2]} ${txt[$[1+($RANDOM%100)]]}"
echo ""
sleep 4s
apt-get install zip -y > /dev/null
apt-get install apache2 -y > /dev/null 2>&1
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
if [ -e "$insta_arquivos1" ]; then
rm -rf $insta_arquivos1
fi
mkdir $insta_arquivos1
mkdir $insta_arquivos2
unzip $HOME/server.zip
rm -rf $HOME/server.zip
mv -f $HOME/etc/adm-server/adm-ultimate/* $insta_arquivos2/
rm -rf $HOME/etc
mv -f $insta_arquivos2/autoonline /bin/
chmod 777 /bin/*
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[2]} Perfeito, Use o Comando \033[1;31mautoonline${cor[2]}
 para Gerenciar as Suas Keys e
 Atualizar a Base do servidor"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠\033[0m"
}

#===================================#
#CONFIGURACOES GERAIS
#===================================#
insta_arquivos="/etc/adm-server/adm-ultimate"
inst_linkk="https://www.dropbox.com/s/r6vayomdypn9dbh/instalar?dl=0"
#===================================#
clear
ofuscate_fun () {
number=$(expr length $1)
for ((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
if [ "${txt[$i]}" = "." ]; then
txt[$i]="#"
else
 if [ "${txt[$i]}" = "#" ]; then
txt[$i]="."
 fi
fi
if [ "${txt[$i]}" = "1" ]; then
txt[$i]="@"
else
 if [ "${txt[$i]}" = "@" ]; then
txt[$i]="1"
 fi
fi
if [ "${txt[$i]}" = "2" ]; then
txt[$i]="?"
else
 if [ "${txt[$i]}" = "?" ]; then
txt[$i]="2"
 fi
fi
if [ "${txt[$i]}" = "3" ]; then
txt[$i]="&"
else
 if [ "${txt[$i]}" = "&" ]; then
txt[$i]="3"
 fi
fi
if [ ! -e $HOME/tmp ]; then
touch $HOME/tmp
fi
echo -ne "${txt[$i]}" >> $HOME/tmp
done
txtofus=$(cat $HOME/tmp)
if [ -e $HOME/tmp ]; then
rm $HOME/tmp
fi
txt_ofuscatw=$(echo $txtofus | rev)
}


meu_ip () {
MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MEU_IP2=$(wget -qO- ipv4.icanhazip.com)
if [[ "$MEU_IP" != "$MEU_IP2" ]]; then
IP="$MEU_IP2"
 else
IP="$MEU_IP"
fi
#PREENXE A VARIAVEL $IP
}

echo -e "\033[1;32m =∞=∞=∞=∞=∞=∞=∞=∞="
echo -e "\033[1;37m GENERADOR KEY! - @barcewin"
echo -e "\033[1;32m =∞=∞=∞=∞=∞=∞=∞=∞="
echo -e "\033[1;31m |1| \033[1;32m=== \033[1;33mACTUALIZAR "
echo -e "\033[1;31m |2| \033[1;32m=== \033[1;33mCREAR KEY "
echo -e "\033[1;32m =∞=∞=∞=∞=∞=∞=∞=∞=\033[1;32m"
read -p " [ 1 - 2 ]-> " op_op
if [ "$op_op" = "1" ]; then
atualiza_fun
exit
fi


echo -e "\033[1;32m=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠\033[1;33m"
key_temp="$RANDOM"
read -p "Créditos del Script: " credit
read -p "Tiempo de la key online en minutos: " time_key
echo -e "\033[1;32m=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
if [ ! -e /var/www/html ]; then
mkdir /var/www/html
fi
mkdir /var/www/$key_temp
mkdir /var/www/$key_temp/install
mkdir /var/www/html/$key_temp
mkdir /var/www/html/$key_temp/install
cp $insta_arquivos/* /var/www/html/$key_temp/install/
cp $insta_arquivos/* /var/www/$key_temp/install/
echo -e "$credit" > /var/www/$key_temp/install/menu_credito
echo -e "$credit" > /var/www/html/$key_temp/install/menu_credito
touch /var/www/$key_temp/lista
touch /var/www/html/$key_temp/lista
meu_ip
for lista in `ls /var/www/html/$key_temp/install`; do
echo -e "$IP:81/$key_temp/install/$lista" >> /var/www/html/$key_temp/lista
echo -e "$IP:81/$key_temp/install/$lista" >> /var/www/$key_temp/lista
done
echo -e "\033[1;91mKEY DE INSTALACION! COPIE Y MANDE AL CLIENTE!\033[0m"
echo -e "\033[1;32m=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
ofuscate_fun $IP:81
echo -e "\033[1;33mINSTALADOR PARA PC => apt-get update; apt-get upgrade; wget http://bnetservice.com.mx/adm/instalarold; bash instalarold"
echo -e "\033[1;97m----------------------------------------"
echo -e "\033[1;33mINSTALADOR PARA MOVIL => apt-get update; apt-get upgrade; wget http://bnetservice.com.mx/adm/instalar bash instalar"
echo -e "\033[1;33mKEY =>\033[1;41m${txt_ofuscatw}∆${key_temp}\033[0m"
echo -e "\033[1;32m=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠\033[0m"
if [ "$time_key" = "" ]; then
time_key="30"
fi
u_dir="$RANDOM"
echo "if [ -d /var/www/html/$key_temp ]; then
rm -rf /var/www/html/$key_temp
fi
if [ -d /var/www/$key_temp ]; then
rm -rf /var/www/$key_temp
fi
rm /bin/$u_dir" > /bin/$u_dir
chmod +x /bin/$u_dir
at -f /bin/$u_dir now + $time_key min > /dev/null 2>&1
exit

